<template lang="pug">
  div(style='display:none;')
    div(itemscope itemtype='http://schema.org/Person')
      img(alt='Profile' itemprop='image' src='../assets/profile.jpg')
      meta(:content='$store.name' itemprop='name')
      meta(:content='$store.job_title' itemprop='jobTitle')
      meta(:content='$store.phone | spaces(4)' itemprop='telephone')
      meta(:content='$store.email' itemprop='email')
    div(itemscope itemtype='http://schema.org/Organization')
      meta(:content='$store.title' itemprop='name')
      div(itemprop='address' itemscope itemtype='http://schema.org/PostalAddress')
        meta(:content='$store.address.street' itemprop='streetAddress')
        meta(:content='$store.address.zipcode' itemprop='postalCode')
        meta(:content='$store.address.city' itemprop='addressLocality')
        meta(:content='$store.address.country' itemprop='addressCountry')
        meta(:content='$store.phone | spaces(4)' itemprop='telephone')
        meta(:content='$store.email' itemprop='email')
      a(:href='$store.url' itemprop='url') {{$store.title}} - {{$store.job_title}}
    div(itemscope itemtype='http://schema.org/Place')
      div(itemprop='geo' itemscope itemtype='http://www.schema.org/GeoCoordinates')
        meta(:content='$store.home_position.lat' itemprop='latitude')
        meta(:content='$store.home_position.lng' itemprop='longitude')
</template>
